// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxrXoExbkEx2QAboDsVjGRZNiH2zhf6Q',
    appId: '1:429865675042:web:613ef04efc96d0bc715d7b',
    messagingSenderId: '429865675042',
    projectId: 'mealdb-recipes-ab80a',
    authDomain: 'mealdb-recipes-ab80a.firebaseapp.com',
    storageBucket: 'mealdb-recipes-ab80a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOA14bNFxnUCSgmoSEkE93FZpJpUPnPGo',
    appId: '1:429865675042:android:171c39e4d0d2986f715d7b',
    messagingSenderId: '429865675042',
    projectId: 'mealdb-recipes-ab80a',
    storageBucket: 'mealdb-recipes-ab80a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTIE_5wIVZLqi0JeCCydpLrvghW7IX30',
    appId: '1:429865675042:ios:d9713dde0497b275715d7b',
    messagingSenderId: '429865675042',
    projectId: 'mealdb-recipes-ab80a',
    storageBucket: 'mealdb-recipes-ab80a.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmTIE_5wIVZLqi0JeCCydpLrvghW7IX30',
    appId: '1:429865675042:ios:d9713dde0497b275715d7b',
    messagingSenderId: '429865675042',
    projectId: 'mealdb-recipes-ab80a',
    storageBucket: 'mealdb-recipes-ab80a.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxxrXoExbkEx2QAboDsVjGRZNiH2zhf6Q',
    appId: '1:429865675042:web:33c026ae12ee60a6715d7b',
    messagingSenderId: '429865675042',
    projectId: 'mealdb-recipes-ab80a',
    authDomain: 'mealdb-recipes-ab80a.firebaseapp.com',
    storageBucket: 'mealdb-recipes-ab80a.firebasestorage.app',
  );
}
